# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'
          ndk: '21.3.6528147'

      - name: Install Haxe
        run: sudo add-apt-repository ppa:haxe/releases -y
        
      - name: Update package list
        run: sudo apt-get update
        
      - name: Install Haxe and Haxelib
        run: sudo apt-get install haxe -y

      - name: Install Haxelib
        run: |
          haxelib install hxcpp > /dev/null
          haxelib install polymod
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib --never install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons 2.11.0
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0 
          haxelib set openfl 9.1.0 
          haxelib set flixel 4.11.0
          haxelib set flixel-addons 2.11.0
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -release

      - name: Publish Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
